{"name": "Проверка неуспешной авторизации с невалидными данными", "status": "passed", "parameters": [{"name": "user_data", "value": "{'password': 'password', 'name': 'Username'}"}], "start": 1732195089276, "stop": 1732195093565, "uuid": "86d47381-d5e3-4d98-b1fa-3e4a21e80f67", "historyId": "0d7eac89450ac66f7e3bcd5e7956cce2", "testCaseId": "c624507b88d3811eb3f5ad3f0dbfed58", "fullName": "tests.test_login_user.TestLoginUser#test_autorization_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-APHBTB3O"}, {"name": "thread", "value": "14376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}